leanflutter/window_manager

- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
fix #25 
给 handleWindowProc  的 result 加了一个 nullopt 初始值。
发现不给赋值为 nullopt 的话，那这个消息还是会被视为已消耗。这个会导致放大缩小之类操作没有系统动画。
> initial handleWindowProc result to nullopt

- windows/window_manager_plugin.cpp
So I did some testing and found that these codes:
- Enables resizing from all border sides.
- Makes it so that the window doesn't resize that much (reduces only one pixel on the left, right, and bottom border) when changing titleBarStyle to "hidden".
- Removing the WM_NCHITTEST makes the edges (top left, bottom right, etc) resize region bigger than it should be.
- fOnResizeBorder should've been set to true (it was set to false) to enable resizing from top border.
Issues: 
- The top side originally goes inside the title bar so someone has to figure out how to do that in titleBarStyle = "hidden".
The top border IS resizable in titleBarStyle = "hidden" but only for exactly 1 pixel and that is very annoying.
- SetResizable makes weird behavior (as usual) during titleBarStyle = "hidden"
> Fix WM_NCCALCSIZE,WM_NCHITTEST: All Border Resize

- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
Basically
- Adds a new variable is_resizable to check if window is/n't resizable.
- Changes IsResizable() to return is_resizable and SetResizable to change is_resizable.
- If not is_resizable, WM_NCHITTEST returns HTNOWHERE which makes hovering and clicking the edges of the window does nothing.
> Alternative method / workaround for setResizable

- lib/src/window_listener.dart
- lib/src/window_manager.dart
- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
This may allow users to intercept `WM_CLOSE` event (thus prevent the window being close), and receive an onclose event.
> OnClose event with intercept option

- lib/src/window_manager.dart
- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
- Enables animation/transition during minimize, maximize, etc (aero) on titleBarStyle = "hidden"
- Added a bug that removes top resize border except for the top left and top right
This is a temporary solution until we can somehow implement
https://github.com/rossy/borderless-window
and/or
https://github.com/melak47/BorderlessWindow
- Added startResize() method on Windows in case someone (me) wants to make a workaround widget for the top resize border
> [Windows] Fix animation titlebar=hidden, add startResize()

- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
- Enables resetting window style to TitleBarStyle.normal/hidden from setAsFrameless(). Fixes #68 
- Removes crazy jittering when resizing window
- Starting point for window border removal (not yet working)
> [Windows] Remove border, setAsFrameless: Enable reset to TitleBarStyle, remove resizing jitter

- windows/window_manager.cpp
Previously, when going back from full screen to normal on frameless (SetAsFrameless()), it will call SetTitleBarStyle() regardless (which cancels out SetAsFrameless). Now, if previously SetAsFrameless(), call SetAsFrameless instead.
> [Windows] Restore setAsFrameless after SetFullScreen(false)

- lib/src/window_manager.dart
- windows/window_manager.cpp
- Add `visibleSize` and `visiblePosition` for `getPrimaryDisplay`
> [Windows] Fix #112: Add visibleSize and visiblePosition

- linux/window_manager_plugin.cc
The Wayland backend of GDK requires the event's source device and local x & y coordinates.
> [Linux] fix popUpWindowMenu() on Wayland

- linux/window_manager_plugin.cc
The proposal is to force prevent_close=false and the close the window
because calling `gtk_widget_destroy()` seems to be too intrusive:
```
** (window_manager_example:1388137): CRITICAL **: 21:09:18.736: gboolean fl_binary_messenger_send_response(FlBinaryMessenger *, FlBinaryMessengerResponseHandle *, GBytes *, GError **): assertion 'FL_IS_BINARY_MESSENGER(self)' failed
```
> [Linux] implement destroy

- linux/window_manager_plugin.cc
`fl_method_success_response_new()` does not take ownership of the value
but increments its reference count by one. Using `g_autoptr` is an
"easy" way to ensure that the newly allocated values get unreferenced
at the end of the scope and that way released as appropriate when the
success response is done with them.
> [Linux] fix method response memory leaks

- linux/window_manager_plugin.cc
This fixes the following build error:
```
window_manager_plugin.cc:527:26: error: unused function 'get_primary_display' [-Werror,-Wunused-function]
```
> [linux] remove unused get_primary_display()

- macos/Classes/WindowManager.swift
window.currentEvent may be nil when call this method rapidly that will cause crash
> [macos]fix crash lead by fast clicks

- lib/src/widgets/virtual_window_frame.dart
Currently the virtual frame has border radius even in maximize or full screen state, this PR removes that.
Normal Window:
Maximized Window:
> Remove decoration for maximized window

- linux/window_manager_plugin.cc
Hi from [RustDesk](https://github.com/rustdesk/rustdesk)!
This PR includes fixes for dragging window issue on **Linux**.
Problems: Cannot drag again immediately after a successful drag. (can drag -> cannot drag -> can drag -> cannot drag ...)
- use GestureDetector.onPanDown to trigger `windowManager.startDragging`, window successfully being moved. Then we release mouse, and want to drag again. It does not works, the window does not moved. We need to drag again, and it works.
Solutions: (inspired by [bitsdojo_window](https://github.com/bitsdojo/bitsdojo_window))
- gtk_drag influences button release event, which affects flutter click logic. So the workaround is to send a button release event to event box.
> [Linux] fix: cannot drag again after startDragging

- linux/window_manager_plugin.cc
Resizing by bottom left, bottom or bottom right were not working correctly on Linux.
With this change they behave like the correct edge.
> Linux: fix bottom edge resizing

- linux/window_manager_plugin.cc
I've found there's an issue when using `gtk_widget_hide` method, causing offset lost after hide the window (always center).
Reproduce repo(pure empty flutter project + window_manager): https://github.com/Kingtous/hide_and_show_issue_reproduce_demo
Note that this is NOT a issue in `window_manager`, but gtk is.
gtk hide will reset offset of the window.
btw, i can reproduce this behavior of gtk also in [rust code](https://github.com/Kingtous/rust-collections/blob/master/examples/gtk-window.rs).
But if I saved the size and offset before hide, and set them once after invoking hide, it behaves normally.
So I add a workaround to make linux able to remember offset and size after hide, which uniforms behaviors of all platforms supported by `window_manager`. (the position and offset of the window …
> fix: offset lost after invoking gtk hide on linux

- .gitignore
- macos/Classes/WindowManager.swift
Foundation/NSNumber.swift:467: Fatal error: Unable to bridge NSNumber to Float
> Fix Unable to bridge NSNumber to Float

- linux/window_manager_plugin.cc
When it comes to hiding the window title bar, there are a few cases to consider.
1. The default Flutter app template defaults to a server-side decorated window title on non-GNOME X11 desktops.
2. Any desktop running on Wayland, and GNOME on X11, default to a client-side decorated `GtkHeaderBar`.
3. Furthermore, the [handy_window](https://pub.dev/packages/handy_window) package, which is popular in Flutter-based Ubuntu apps, provides a more modern-looking `HdyWindow` with rounded bottom corners and the header bar replaced by `HdyHeaderBar`.
This PR ensures that `setTitleBarStyle()` works in all these three cases on Linux.
> Linux: make `setTitleBarStyle()` GTK/HDY/CSD/SSD compatible

- linux/window_manager_plugin.cc
This is a replacement of #248 and implements support for frameless windows and background colors in a way that it doesn't draw over [HdyWindow](https://pub.dev/packages/handy_window)'s shadows nor needs any redraw tricks.
> Linux: fix frameless window & background color

- lib/src/window_manager.dart
An error is thrown when we call setMaximizable because we are using invokeListMethod, instead of invokeMethod.
- Replace invokeListMethod with invokeMethod
- Modify method to be asynchronous
Fixes https://github.com/leanflutter/window_manager/issues/219
> [Windows] Fix set maximizable throwing an error

- linux/window_manager_plugin.cc
The return value of [gtk_window_get_title()](https://docs.gtk.org/gtk3/method.Window.get_title.html) may be null.
> [linux] fix `getTitle()` crash when null

- linux/window_manager_plugin.cc
The [GtkWidget::show](https://docs.gtk.org/gtk3/vfunc.Widget.show.html) and [GtkWidget::hide](https://docs.gtk.org/gtk3/vfunc.Widget.hide.html) signals do not have any "event" argument. It's important to have the correct signature to ensure that the user data argument points to the correct memory address.
> [linux] fix `on_window_show` and `on_window_hide` signatures

- linux/window_manager_plugin.cc
These are implemented in terms of the current window state and type to make them match with the native window popup menu (e.g. a dialog always has minimize and maximize items dimmed in the menu).
> [linux] implement minimizable & maximizable

- lib/src/window_manager.dart
Make sure to return futures so that they can be awaited if necessary.
> Add missing future return values

- lib/src/window_manager.dart
> Don't crash if an event doesn't have a dedicated handler

- linux/window_manager_plugin.cc
If a window doesn't have a textual title set at all, don't remove its decorations (shadows) when calling `setTitleBarStyle(hidden)`.
> Linux: avoid removing shadows if no title is set

- example/linux/my_application.cc
- lib/src/widgets/virtual_window_frame.dart
To avoid first displaying a window as Server-side Decoration and then changing it to Client-side Decoration.
Use 'gtk_widget_realize' instead of 'gtk_widget_show' in the example.
> [linux] remove the margins of the window frame

- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
Current implemention of setMinimum/MaximumSize() on Windows platform only get device pixel ratio once at the functions called.  When user has multiple monitors with different dpi, this implementation will cause window size issue (too big / small) after drag the window to another monitor.
This PR implements dpi change awareness feature for setMinimum/MaximumSize().
> [Windows] make setMinimum/MaximumSize() dpi change awareable

- linux/window_manager_plugin.cc
Currently on Linux using `setAsFrameless` can't be undone; with this change using `setTitleBarStyle(TitleBarStyle.normal)` will also restore the window frame.
Follows the same sort of resolution as https://github.com/leanflutter/window_manager/pull/103
> feat: setTitleBarStyle() restores window frame on Linux

- README.md
From the documentation of `initState()` of the `State` class: "Implementations of this method should start with a call to the inherited method, as in super.initState()." (https://api.flutter.dev/flutter/widgets/State/initState.html). So to make sure the examples conform with the contract of this method I moved the calls to `super.initState()` to the beginning in each of the overrides.
Obviously I'm assuming that this does not have any impact on the windowManager-related logic, but I could be wrong. In that case, a small comment or an explanation in the documentation as to why it is necessary to do it this way would be useful.
> Moved calls to `super.initState()` to the top of overrides to conform with documented method contract

- macos/Classes/WindowManager.swift
fixes Foundation/NSNumber.swift:467: Fatal error: Unable to bridge NSNumber to Float
> fixes setMinimumSize and setMaximumSize on macos

- linux/window_manager_plugin.cc
This PR adds a workaround to remove the `delete-event` handlers in the flutter engine on Linux, which breaks the propagation of `on-close` event.
Note that it only happens on flutter >= 3.10, and the problem is brought by https://github.com/flutter/engine/pull/40033#discussion_r1200216166.
Future: this pr may break some latest api provided by Flutter, but currently we must fix the `setPreventClose` to ensure the validity of this important and core function. latest api: https://github.com/flutter/flutter/issues/30735
> fix: on-close event handler not be triggered on flutter >= 3.10

- example/lib/pages/home.dart
- lib/src/window_manager.dart
- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
Uses a modified method suggested by [this comment by @alexmercerind](https://github.com/leanflutter/window_manager/pull/359#pullrequestreview-1501577990), which in general reduces flicker when going to full screen and just behaves more predictable.
Todo:
1. Native window title bar is removed.
2. Remove/hide custom title bar widget (Developers should do this themselves).
3. Borders (including the rounded corners) are removed
4. Window is maximized to fit the whole screen.
5. Prevent the user from resizing the window (disables `startResizing()`)
6. Prevent the user from dragging/moving the window (disables `startDragging()`)
> [Windows] Better fullscreen implementation

- windows/window_manager.cpp
The `ShellScalingApi.h` is not supported by Windows 7, so we better load this dynamically.
Related to #347
> feat: restore Windows 7 support

- windows/window_manager_plugin.cpp
- Fixes #389: issue where window cannot `setAsFrameless` doesn't work if called when `titleBarStyle.normal`
> Fix #389 `setAsFrameless` on `titleBarStyle.normal`

- lib/src/window_manager.dart
- Fixes issue where setting both `size` and `setTitleBarStyle` using `WindowOptions` in `waitUntilReadyToShow` causes incorrect window size.
This is fixed by putting `titleBarStyle` handling before all other options so the OS calculates the window size and position correctly,
> fix: incorrect window size before/after `setTitleBarStyle`

- windows/window_manager.cpp
When the Flutter app is displayed in fullscreen mode on an external monitor, the window is not positioned as it should be because the position computed is wrong.
> [Windows] Wrong window position in fullscreen mode with external monitor 

- windows/window_manager.cpp
- windows/window_manager_plugin.cpp
- Fix #396: a critical bug where the newest implementation of fullscreen/unfullscreen broke the window listener events.
- Disables minimize when window is fullscreen. This mimics the behavior of Chromium.
> fix #396: (windows) fullscreen/unfullscreen events, disable minimize on fullscreen

- windows/window_manager.cpp
`WindowManager::IsFocused()` uses `GetActiveWindow()` which returns active window of the current application. It doesn't mean that this application is in foreground and has keyboard focus. The correct way is to use `GetForegroundWindow()` which this PR does.
> Fix WindowManager.IsFocused() method on Windows

- README.md
Adds `UniControlHub` to `who's using it` section of Readme
Note: Am the owner of [UniControlHub](https://github.com/rohitsangwan01/uni_control_hub)
> Add UniControlHub to readme

- windows/window_manager_plugin.cpp
In the default example, the window height is incorrect when maximized.
Windows -> Display settings -> Scale (any value other than 100%)
Win11, scale `150%`, `2160x1440`, `window_manager` as an example (same logic).
1. `cd example && flutter run -d windows`
2. Find the output like `The Flutter DevTools debugger and profiler on Windows is available at: http://127.0.0.1:9105?uri=http://127.0.0.1:65189/_rHWjbz1MZA=/`, open the link.
3. Back the the example window, maxmize the window.
4. Check the window height. The number should be `912`, not `916`.
1. Why the following code is not in the `if (window_manager->IsMaximized())` block
2. Why do you use `9` instead of `8` here?
> fix: windows, window size, fullscree & maximized

- windows/window_manager_plugin.cpp
Monitor 1
https://github.com/user-attachments/assets/2bc66aaf-8274-425c-88e1-3ded21c9ed1c
https://github.com/user-attachments/assets/556fe8d5-e581-40be-ac60-ac50b65eb17f
> fix: win, adjustNCCALCSIZE with monitor coords

- windows/window_manager_plugin.cpp
Fix 439 issue: [Windows] Restoring window from minimized state triggers onWindowBlur instead of onWindowFocus.
> Update window_manager_plugin.cpp for fix 439 issue

- windows/window_manager_plugin.cpp
https://github.com/leanflutter/window_manager/issues/489
Get window monitor when it is restored from minimized state(current maximized),
https://github.com/user-attachments/assets/e8a035f5-1355-413f-a0e4-5277ed2f30b0
> fix: get window monitor from minimized state

- packages/window_manager/linux/window_manager_plugin.cc
When compiling in release mode for linux, the window size constraints (ie. `setMinimumSize`) weren't being enforced.
This happened because the `window_hints` variable was not initialized and contained garbage data (while it was zero in debug mode).
> Initialize window_hints to fix minimum size setting in release mode

- packages/window_manager/lib/src/window_manager.dart
- packages/window_manager/windows/window_manager.cpp
This may fixes #521 and fixes #211 
closes #456.
1. Use `(WS_THICKFRAME | WS_MAXIMIZEBOX)` instead of `WS_OVERLAPPEDWINDOW` can avoid the native title bar appearing on exit fullscreen.
This is inspired by [this article](https://blog.lindexi.com/post/WPF-%E7%A8%B3%E5%AE%9A%E7%9A%84%E5%85%A8%E5%B1%8F%E5%8C%96%E7%AA%97%E5%8F%A3%E6%96%B9%E6%B3%95.html)
2. When the app is not maximized, call `SetAsFrameless` then change the app position and size **separately** (avoid UI stretching). To avoid UI freezing after enter fullscreen, the force refresh is removed.
> [Windows] Use frameless window to implement fullscreen

- packages/window_manager/windows/window_manager_plugin.cpp
Fix crash when using window_manager by multi engine on windows platform. channel should not be gloabal variable.
> Fix crash when using window_manager by multiwin on windows platform

- packages/window_manager/example/lib/pages/home.dart
- packages/window_manager/lib/src/window_manager.dart
- packages/window_manager/windows/window_manager_plugin.cpp
> Add getWindowHandle
